[features]
seeds = false
skip-lint = false

[programs.localnet]
tab_router = "DvS3eW3GJGVJrvqMBtcsS8QtNoxzYtpB61Cx19Uz86xs"
tab_escrow = "FTpukPZPKix4N6Po8obUTwnDvyMqwAqo4EaDFyCnJjMd"
tab_subscription = "Ex1hBmDhmz8hZ7oYy4BKtt5jstEMCoeeshEA51swbXZa"
tab_subscription_personal = "DpQSpSdnwRB1p7iK1b5TbL1F5YqtimGd9g32jWc4WyB7"
tab_bot = "42aU1kQzoXhyPcXb67qrPvQX1Tzx3Uyw4XbfUNF6nEZ8"
tab_escrow_personal = "A583E27BuN3YWP5WmsoFeaYdPtnKMAGU7tHgMrZbqwn"

[programs.devnet]
tab_router = "DvS3eW3GJGVJrvqMBtcsS8QtNoxzYtpB61Cx19Uz86xs"
tab_escrow = "FTpukPZPKix4N6Po8obUTwnDvyMqwAqo4EaDFyCnJjMd"
tab_subscription = "Ex1hBmDhmz8hZ7oYy4BKtt5jstEMCoeeshEA51swbXZa"
tab_subscription_personal = "DpQSpSdnwRB1p7iK1b5TbL1F5YqtimGd9g32jWc4WyB7"
tab_bot = "42aU1kQzoXhyPcXb67qrPvQX1Tzx3Uyw4XbfUNF6nEZ8"
tab_escrow_personal = "A583E27BuN3YWP5WmsoFeaYdPtnKMAGU7tHgMrZbqwn"

[programs.mainnet]
tab_router = "DvS3eW3GJGVJrvqMBtcsS8QtNoxzYtpB61Cx19Uz86xs"
tab_escrow = "FTpukPZPKix4N6Po8obUTwnDvyMqwAqo4EaDFyCnJjMd"
tab_subscription = "Ex1hBmDhmz8hZ7oYy4BKtt5jstEMCoeeshEA51swbXZa"
tab_subscription_personal = "DpQSpSdnwRB1p7iK1b5TbL1F5YqtimGd9g32jWc4WyB7"
tab_bot = "42aU1kQzoXhyPcXb67qrPvQX1Tzx3Uyw4XbfUNF6nEZ8"
tab_escrow_personal = "A583E27BuN3YWP5WmsoFeaYdPtnKMAGU7tHgMrZbqwn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/tab-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
